# pdf_config.py

# Layout
DEFAULT_MARGIN = 10
IMAGE_WIDTH_MM = 20
IMAGE_HEIGHT_MM = 20
LINE_SPACING = 4
HEADER_LINE_WIDTH = 0.5
HEADER_COLUMNS = 5

# Fonts
FONT_FAMILY = "Arial"
FONT_SIZE_TITLE = 16
FONT_SIZE_DESCRIPTION = 12
FONT_SIZE_LABEL = 10
FONT_SIZE_FIELD = 10

# Page
PAGE_WIDTH = 210  # A4 standard width in mm
PAGE_HEIGHT = 297
